// This file is auto-generated by tracey-codegen
// DO NOT EDIT MANUALLY - changes will be overwritten
// Run 'cargo run -p tracey-codegen' to regenerate

/**
 * Spec content (may span multiple files)
 */
export interface ApiSpecData {
  name: string;
  /**
   * Sections ordered by weight
   */
  sections: SpecSection[];
  /**
   * Outline with coverage info
   */
  outline: OutlineEntry[];
}

/**
 * An entry in the spec outline (heading with coverage info)
 */
export interface OutlineEntry {
  /**
   * Heading text
   */
  title: string;
  /**
   * Slug for linking
   */
  slug: string;
  /**
   * Heading level (1-6)
   */
  level: number;
  /**
   * Direct coverage (rules directly under this heading)
   */
  coverage: OutlineCoverage;
  /**
   * Aggregated coverage (includes all nested rules)
   */
  aggregated: OutlineCoverage;
}

/**
 * Coverage counts for an outline entry
 */
export interface OutlineCoverage {
  /**
   * Number of rules with implementation refs
   */
  implCount: number;
  /**
   * Number of rules with verification refs
   */
  verifyCount: number;
  /**
   * Total number of rules
   */
  total: number;
}

/**
 * A section of a spec (one source file)
 */
export interface SpecSection {
  /**
   * Source file path
   */
  sourceFile: string;
  /**
   * Rendered HTML content
   */
  html: string;
  /**
   * Weight for ordering (from frontmatter)
   */
  weight: number;
}

export interface ApiCodeUnit {
  kind: string;
  name?: string;
  startLine: number;
  endLine: number;
  /**
   * Rule references found in this code unit's comments
   */
  ruleRefs: string[];
}

/**
 * Single file with full coverage details
 */
export interface ApiFileData {
  path: string;
  content: string;
  /**
   * Syntax-highlighted HTML content
   */
  html: string;
  /**
   * Code units in this file with their coverage
   */
  units: ApiCodeUnit[];
}

export interface ApiFileEntry {
  path: string;
  /**
   * Number of code units in this file
   */
  totalUnits: number;
  /**
   * Number of covered code units
   */
  coveredUnits: number;
}

/**
 * Reverse traceability: file tree with coverage info
 */
export interface ApiReverseData {
  /**
   * Total code units across all files
   */
  totalUnits: number;
  /**
   * Code units with at least one rule reference
   */
  coveredUnits: number;
  /**
   * File tree with coverage info
   */
  files: ApiFileEntry[];
}

export interface ApiCodeRef {
  file: string;
  line: number;
}

export interface ApiRule {
  id: string;
  html: string;
  status?: string;
  level?: string;
  sourceFile?: string;
  sourceLine?: number;
  implRefs: ApiCodeRef[];
  verifyRefs: ApiCodeRef[];
  dependsRefs: ApiCodeRef[];
}

export interface ApiSpecForward {
  name: string;
  rules: ApiRule[];
}

/**
 * Forward traceability: rules with their code references
 */
export interface ApiForwardData {
  specs: ApiSpecForward[];
}

export interface ApiSpecInfo {
  name: string;
  /**
   * Prefix used in annotations (e.g., "r" for r[req.id])
   */
  prefix: string;
  /**
   * Path to spec file(s) if local
   */
  source?: string;
  /**
   * Available implementations for this spec
   */
  implementations: string[];
}

/**
 * Project configuration info
 */
export interface ApiConfig {
  projectRoot: string;
  specs: ApiSpecInfo[];
}

/**
 * Git status for a file
 */
export type GitStatus = "dirty" | "staged" | "clean" | "unknown";


