//! TypeScript code generator for tracey API types

use facet_typescript::TypeScriptGenerator;
use std::fs;
use std::path::Path;
use tracey_api::*;

fn main() {
    let mut generator = TypeScriptGenerator::new();

    // Add all API types
    generator.add_type::<GitStatus>();
    generator.add_type::<ApiConfig>();
    generator.add_type::<ApiSpecInfo>();
    generator.add_type::<ApiForwardData>();
    generator.add_type::<ApiSpecForward>();
    generator.add_type::<ApiRule>();
    generator.add_type::<ApiCodeRef>();
    generator.add_type::<ApiReverseData>();
    generator.add_type::<ApiFileEntry>();
    generator.add_type::<ApiFileData>();
    generator.add_type::<ApiCodeUnit>();
    generator.add_type::<SpecSection>();
    generator.add_type::<OutlineCoverage>();
    generator.add_type::<OutlineEntry>();
    generator.add_type::<ApiSpecData>();

    // Generate TypeScript code
    let typescript = generator.finish();

    // Add header comment
    let output = format!(
        "// This file is auto-generated by tracey-codegen\n\
         // DO NOT EDIT MANUALLY - changes will be overwritten\n\
         // Run 'cargo run -p tracey-codegen' to regenerate\n\
         \n\
         {}\n",
        typescript
    );

    // Write to dashboard/src/api-types.ts
    let dashboard_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("tracey/dashboard/src");

    let output_path = dashboard_dir.join("api-types.ts");

    fs::write(&output_path, output).expect("Failed to write TypeScript types");

    println!("Generated TypeScript types at: {}", output_path.display());
}
